name: test_component
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: alea <email@example.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular2: 3.1.0
  source_gen: any
  code_builder: any
  quiver: any

transformers:
- angular2:
    entry_points: web/main.dart

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
